# Generated by Django 3.1.1 on 2020-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'male')], default=0, max_length=20),
        ),
    ]
